parameters:
    app.messages_encryption_key: '%env(MESSAGES_ENCRYPTION_KEY)%'
    app.mqtt_host: '%env(string:MQTT_HOST)%'
    app.mqtt_port: '%env(int:MQTT_PORT)%'
    app.mqtt_user: '%env(string:MQTT_USER)%'
    app.mqtt_password: '%env(string:MQTT_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Pour le script CLI create_admin.php (le hasher n'est pas public sur le conteneur)
    app.cli_password_hasher:
        alias: security.user_password_hasher
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CryptoService:
        arguments:
            $messagesEncryptionKey: '%app.messages_encryption_key%'

    App\Service\MqttService:
        arguments:
            $mqttHost: '%app.mqtt_host%'
            $mqttPort: '%app.mqtt_port%'
            $mqttUser: '%app.mqtt_user%'
            $mqttPassword: '%app.mqtt_password%'
